services:
  mysql:
    image: docker.io/bitnami/mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      mysql:
        condition: service_healthy
    command: "sh -c '/usr/local/bin/setup-project.sh'"
    ports:
      - '8000:8000'
      - '5173:5173'
    volumes:
      - '.:/var/www/html:z'

networks:
  default:
    name: enrollment_notification_network
    
volumes:
  mysql_data:
    driver: local